// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUhTuqof3DrlKV7MbostM5HqpbUZl4msk',
    appId: '1:461887391658:web:89d1ce4e4f68055618cdd3',
    messagingSenderId: '461887391658',
    projectId: 'lvm-data',
    authDomain: 'lvm-data.firebaseapp.com',
    storageBucket: 'lvm-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8XwCezkQAz-d22jDk910wJxe_WzIxuDU',
    appId: '1:461887391658:ios:1f403bb6eb61a4c018cdd3',
    messagingSenderId: '461887391658',
    projectId: 'lvm-data',
    storageBucket: 'lvm-data.firebasestorage.app',
    iosClientId: '461887391658-kms4mdo2di2d7g3jb7qb3qniflm4ria6.apps.googleusercontent.com',
    iosBundleId: 'com.example.voicemaskFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8XwCezkQAz-d22jDk910wJxe_WzIxuDU',
    appId: '1:461887391658:ios:1f403bb6eb61a4c018cdd3',
    messagingSenderId: '461887391658',
    projectId: 'lvm-data',
    storageBucket: 'lvm-data.firebasestorage.app',
    iosClientId: '461887391658-kms4mdo2di2d7g3jb7qb3qniflm4ria6.apps.googleusercontent.com',
    iosBundleId: 'com.example.voicemaskFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDnjL0exvnvbU_vklhCh6qgDWJClSY1_o',
    appId: '1:461887391658:web:39324d30a18e1d3118cdd3',
    messagingSenderId: '461887391658',
    projectId: 'lvm-data',
    authDomain: 'lvm-data.firebaseapp.com',
    storageBucket: 'lvm-data.firebasestorage.app',
  );
}
